version: '3'

# docker volumeという概念らしい
volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/product-register'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true
    stdin_open: true
    # dbサービスができたらwebを作る。docker-compose独自概念
    depends_on:
      - db
    # webからdbにアクセスできるようにする。docker-compose独自概念
    links:
      - db

  db:
    image: postgres
    volumes:
      # 左辺はdocker volume
      # 右辺はデフォルトのpostgreの保存場所
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD'=trust